project_id = "ldfhcfkflzgebnehbanr"

[functions.abandoned-cart-email]
verify_jwt = false

[functions.verify-admin-passcode]
verify_jwt = false

[functions.fetch-exchange-rates]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = false
 
 [functions.send-order-notification-email]
 verify_jwt = false
